# Generated by Django 6.0.1 on 2026-06-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0005_checkout_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramOrderSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(max_length=64, verbose_name="Telegram chat id"),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Telegram user id"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telegram username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="First name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_notified_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Last notified order status",
                    ),
                ),
                (
                    "last_notified_payment_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Last notified payment status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_subscriptions",
                        to="shop.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram order subscription",
                "verbose_name_plural": "Telegram order subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["telegram_chat_id", "is_active"],
                        name="telegram_sub_chat_active_idx",
                    ),
                    models.Index(
                        fields=["order", "is_active"],
                        name="telegram_sub_order_active_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "telegram_chat_id"),
                        name="unique_telegram_order_subscription",
                    )
                ],
            },
        ),
    ]
