# Generated by Django 6.0.1 on 2026-03-02 19:06

import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteLanguageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_uk",
                    models.BooleanField(default=True, verbose_name="Enable Ukrainian"),
                ),
                (
                    "enable_en",
                    models.BooleanField(default=True, verbose_name="Enable English"),
                ),
                (
                    "enable_pl",
                    models.BooleanField(default=True, verbose_name="Enable Polish"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Site language settings",
                "verbose_name_plural": "Site language settings",
            },
        ),
        migrations.AlterField(
            model_name="producttranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="shop.product",
            ),
        ),
    ]
