# Generated by Django 6.0.1 on 2026-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_checkout_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_note",
            field=models.TextField(
                blank=True,
                help_text="Visible to customers in Telegram status updates.",
                verbose_name="Status note",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending payment"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("ready_for_delivery", "Ready for delivery"),
                    ("out_for_delivery", "Courier is on the way"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("fulfilled", "Fulfilled"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
