# Generated by Django 6.0.1 on 2026-06-15 13:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_order_provider_payment_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Provider order ID",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Provider payment ID",
                    ),
                ),
                (
                    "payment_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Payment payload"
                    ),
                ),
                (
                    "payment_status_token_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Payment status token hash",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shop.subscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription payment",
                "verbose_name_plural": "Subscription payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
