# Generated by Django 6.0.1 on 2026-06-15 18:08

import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_subscriptionplan_translatable"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="target_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upgrade_payments",
                to="shop.subscriptionplan",
                verbose_name="Target plan",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("canceled", "Canceled"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplantranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="shop.subscriptionplan",
            ),
        ),
    ]
