# Generated by Django 6.0.1 on 2026-06-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_add_target_plan_to_subscription_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="badge",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Badge"
            ),
        ),
    ]
