# Generated by Django 6.0.1 on 2026-06-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_add_badge_to_subscription_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="badge",
        ),
        migrations.AddField(
            model_name="subscriptionplantranslation",
            name="badge",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Badge"
            ),
        ),
    ]
