# Generated by Django 6.0.1 on 2026-06-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_add_promo_codes_and_discounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="provider_order_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Provider order ID",
            ),
        ),
    ]
