# Generated by Django 6.0.1 on 2026-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_subscription_payment_provider_order_id_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="provider_order_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Provider order ID",
            ),
        ),
    ]
