# Generated by Django 6.0.1 on 2026-06-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_subscription_payment_provider_order_id_null_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
