# Generated by Django 6.0.1 on 2026-07-02 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_raise_default_bouquet_prices"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Previous status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("ready_for_delivery", "Ready for delivery"),
                            ("out_for_delivery", "Courier is on the way"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("fulfilled", "Fulfilled"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=20,
                        verbose_name="New status",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'webhook', 'admin change', 'payment confirmation'",
                        max_length=100,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Changed at"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="shop.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order status log",
                "verbose_name_plural": "Order status logs",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-changed_at"],
                        name="shop_orders_order_i_3bb365_idx",
                    )
                ],
            },
        ),
    ]
