# Generated by Django 6.0.1 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_category_categorycontentblock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycontentblock",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to="categories/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to="products/",
                verbose_name="Image",
            ),
        ),
    ]
