# Generated by Django 6.0.1 on 2026-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_alter_categorycontentblock_image_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorycontentblock",
            name="align",
            field=models.CharField(
                choices=[
                    ("left", "Left (default)"),
                    ("center", "Center"),
                    ("right", "Right"),
                ],
                default="left",
                help_text="Applies to the heading, text, and image of this block.",
                max_length=10,
                verbose_name="Alignment",
            ),
        ),
        migrations.AddField(
            model_name="categorycontentblock",
            name="heading_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "H1 — page title (largest)"),
                    (2, "H2 — section title (default)"),
                    (3, "H3 — subsection"),
                    (4, "H4 — small heading"),
                    (5, "H5 — smaller"),
                    (6, "H6 — smallest"),
                ],
                default=2,
                help_text="H1 is the largest, H6 the smallest.",
                verbose_name="Heading size",
            ),
        ),
        migrations.AddField(
            model_name="categorycontentblock",
            name="image_radius",
            field=models.CharField(
                choices=[
                    ("none", "Square corners"),
                    ("soft", "Soft corners (default)"),
                    ("large", "Very round corners"),
                ],
                default="soft",
                help_text="Corner rounding of the image.",
                max_length=10,
                verbose_name="Image corners",
            ),
        ),
        migrations.AddField(
            model_name="categorycontentblock",
            name="image_size",
            field=models.CharField(
                choices=[
                    ("small", "Small (~1/3 width)"),
                    ("medium", "Medium (~2/3 width)"),
                    ("full", "Full width (default)"),
                ],
                default="full",
                help_text="How wide the image appears on the page.",
                max_length=10,
                verbose_name="Image size",
            ),
        ),
    ]
