export const API_ROUTES = {
  PRODUCTS: 'products',
  CHECKOUT: 'orders/checkout',
  FAVORITES: 'favorites',
  CART: 'cart',
  AUTH_SIGN_IN: 'auth/token/',
  AUTH_SIGN_UP: 'auth/register/',
  AUTH_REFRESH_TOKEN: 'auth/refresh/',
  AUTH_SIGN_OUT: 'auth/logout/',
  AUTH_ME: 'auth/me/',
  ROLES: 'roles',
  SUBSCRIPTIONS: 'subscriptions',
  SUBSCRIBE: 'subscriptions/subscribe',
  UNSUBSCRIBE: 'subscriptions/unsubscribe',
};
