import bouquetRoses from '@/assets/bouquet-roses.jpg';
import bouquetPeony from '@/assets/bouquet-peony.jpg';
import bouquetWild from '@/assets/bouquet-wild.jpg';
import heroFlowers from '@/assets/hero-flowers.jpg';
import subscriptionBox from '@/assets/subscription-box.jpg';
import type { CatalogItem } from '@/types/catalog';

export const catalogItems: CatalogItem[] = [
  {
    id: '1',
    name: 'Романтичні троянди',
    description: 'Ніжний букет з рожевих та білих троянд',
    price: 1850,
    image: bouquetRoses,
    tag: 'Бестселер',
  },
  {
    id: '2',
    name: 'Лавандова елегантність',
    description: 'Білі півонії з гілочками лаванди',
    price: 2200,
    image: bouquetPeony,
    tag: 'Новинка',
  },
  {
    id: '3',
    name: 'Сонячний настрій',
    description: 'Соняшники та польові квіти',
    price: 1650,
    image: bouquetWild,
    tag: 'Популярне',
  },
  {
    id: '4',
    name: 'Перлинний ранок',
    description: 'Півонії, еустоми та легка зелень',
    price: 1950,
    image: bouquetPeony,
    tag: 'Преміум',
  },
  {
    id: '5',
    name: 'Медовий сад',
    description: 'Теплі троянди з гіпсофілою та рускусом',
    price: 1780,
    image: bouquetRoses,
    tag: 'Хіт тижня',
  },
  {
    id: '6',
    name: 'Поле мрій',
    description: 'Мікс ромашок, волошок та польових квітів',
    price: 1500,
    image: bouquetWild,
    tag: 'Сезонне',
  },
  {
    id: '7',
    name: 'Весняна симфонія',
    description: 'Тюльпани, ранункулюси та ароматна зелень',
    price: 2100,
    image: heroFlowers,
    tag: 'Новинка',
  },
  {
    id: '8',
    name: 'Вечірній шарм',
    description: 'Бордова троянда з евкаліптом та стрічками',
    price: 2350,
    image: bouquetRoses,
    tag: 'Преміум',
  },
  {
    id: '9',
    name: 'Пастельний бриз',
    description: 'Півонії та кремові троянди в пастелі',
    price: 2050,
    image: bouquetPeony,
    tag: 'Ліміт',
  },
  {
    id: '10',
    name: 'Квіткова коробка "Ніжність"',
    description: 'Композиція у стильній коробці з лагідними квітами',
    price: 2600,
    image: subscriptionBox,
    tag: 'Подарунок',
  },
  {
    id: '11',
    name: 'Біла класика',
    description: 'Білі троянди та лілії для особливих подій',
    price: 1900,
    image: heroFlowers,
    tag: 'Класика',
  },
  {
    id: '12',
    name: 'Лісова казка',
    description: 'Зелень, сухоцвіти та природні фактури',
    price: 1700,
    image: bouquetWild,
    tag: 'Eco',
  },
  {
    id: '13',
    name: 'Рожевий кварц',
    description: 'Рожеві троянди та ранункулюси',
    price: 2000,
    image: bouquetRoses,
    tag: 'Популярне',
  },
  {
    id: '14',
    name: 'Акварельний настрій',
    description: 'Мікс пастельних відтінків та легкої зелені',
    price: 1750,
    image: bouquetPeony,
    tag: 'Сезонне',
  },
  {
    id: '15',
    name: 'Золотий захід',
    description: 'Соняшники, хризантеми та медові тони',
    price: 1680,
    image: bouquetWild,
    tag: 'Теплі тони',
  },
];
